# Do not change version. This is the version of aws buildspec, not the version of your buildspec file.
version: 0.2

env:
  parameter-store:
    CONTEXT: /${CODE_PIPELINE_NAME}/CONTEXT
    SCRIVITO_ORIGIN: /${CODE_PIPELINE_NAME}/SCRIVITO_ORIGIN
    SCRIVITO_TENANT: /${PROJECT_NAME}/SCRIVITO_TENANT
    URL: /${CODE_PIPELINE_NAME}/URL

phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - rm -rf design node_modules
      - rm -f build.zip

artifacts:
  files:
    - '**/*'
